title: Zoomba
url: https://supah32.github.io/pie-2022-03/
# logo: "/assets/images/kd.png"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
repository: supah32/pie-2022-03
base_url: "/pie-2022-03/"

markdown: "kramdown"

plugins:
 - jekyll-feed
 - jekyll-include-cache
 - jekyll-target-blank

# Disables RSS feed icon
atom_feed:
  hide: true

header:
  show_overlay_excerpt: false

footer:
  links:
    - label: "Project Repo"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ayushchakra/autonomous-robot-vacuum"
    - label: "Website Repo"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/supah32/pie-2022-03/tree/master"

defaults:
  - values:
      layout: single

include:
  - _pages
#   - _data
